name: runpipeline

run-name: run pipelines
on:
  push:
    branches:
      - cicd
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: ${{secrets.CI_DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.CI_DB_PASSWORD}}
          POSTGRES_DB: db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21.0.1
        uses: actions/setup-java@v3
        with:
          java-version: '21.0.1'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml